package cn.qwenpaw.android;

import android.os.Bundle;
import android.text.*;
import android.view.*;
import android.widget.*;
import com.google.android.material.dialog.MaterialAlertDialogBuilder;
import io.noties.markwon.Markwon;
import io.noties.markwon.ext.tables.TablePlugin;
import io.noties.markwon.ext.strikethrough.StrikethroughPlugin;
import io.noties.markwon.ext.tasklist.TaskListPlugin;
import org.json.*;
import java.util.*;

/** Agent Skills and global Skill Pool; intentionally no create, ZIP, URL or market flows. */
public final class SkillsActivity extends ManagementActivity {
    private boolean pool,editing;
    private JSONArray skills=new JSONArray();
    private final LinkedHashSet<String> selected=new LinkedHashSet<>();
    private String query="",filter="全部",tag="全部标签";
    private LinearLayout list;
    private TextView selection;
    private JSONObject detail;
    private EditText config;
    private Markwon markdown;
    private String originalName="",originalConfig="";

    @Override public void onCreate(Bundle state){super.onCreate(state);if(account==null)return;pool=getIntent().getBooleanExtra("pool",false);markdown=Markwon.builder(this).usePlugin(TablePlugin.create(this)).usePlugin(StrikethroughPlugin.create()).usePlugin(TaskListPlugin.create(this)).build();screen(pool?"技能池管理":"技能",!pool,()->leaveEditor(()->load(true)));showList();load(false);}
    @Override protected void onAgentChanged(){editing=false;detail=null;selected.clear();query="";showList();load(false);}
    @Override protected void working(boolean value){super.working(value);if(agentSelector!=null)agentSelector.setEnabled(!value&&!editing);}
    private String prefix(){return pool?"/skills/pool":"/skills";}
    private String path(String skill){return prefix()+"/"+ApiClient.enc(skill);}
    private void load(boolean hard){task("正在读取技能…",api->array(api.call(hard?"POST":"GET",prefix()+(hard?"/refresh":""),null)),data->{skills=data;detail=null;selected.removeIf(n->!containsName(data,n));showList();});}
    private static boolean containsName(JSONArray data,String name){for(int i=0;i<data.length();i++)if(name.equals(Json.object(data.opt(i)).optString("name")))return true;return false;}
    private void showList(){
        editing=false;if(agentSelector!=null)agentSelector.setEnabled(true);body.removeAllViews();
        LinearLayout intro=card(body);intro.addView(ui.heading(pool?"集中管理，按需分发":"让智能体掌握更多能力",20));ui.gap(intro,8);text(intro,pool?"维护当前账号的技能池，选择智能体分发；支持配置、更新和自动同步，技能正文只读预览。":"技能仅作用于当前选中的智能体。启用后可在对话中使用，技能正文只读预览。");
        EditText search=field(body,"搜索技能名称或描述",query,false);
        LinearLayout filters=ui.row();Spinner state=compactSpinner(filters,pool?List.of("全部","内置","自定义","外部","自动同步"):List.of("全部","已启用","未启用","预加载"),filter);
        TreeSet<String> tags=new TreeSet<>();for(int i=0;i<skills.length();i++){JSONArray a=Json.array(Json.object(skills.opt(i)).opt("tags"));for(int j=0;j<a.length();j++)tags.add(a.optString(j));}ArrayList<String> tagOptions=new ArrayList<>(List.of("全部标签"));tagOptions.addAll(tags);if(!tagOptions.contains(tag))tag="全部标签";Spinner tagSelect=compactSpinner(filters,tagOptions,tag);body.addView(filters);
        state.setContentDescription("技能状态筛选");tagSelect.setContentDescription("技能标签筛选");
        selectChanged(state,value->{filter=value;renderList();});selectChanged(tagSelect,value->{tag=value;renderList();});
        LinearLayout actions=ui.row();actions.addView(ui.button("批量管理",null,false,v->batchMenu()),new LinearLayout.LayoutParams(0,-2,1));actions.addView(ui.button(pool?"导入内置技能":"从技能池下载",null,false,v->{if(pool)builtins();else downloadPicker();}),new LinearLayout.LayoutParams(0,-2,1));body.addView(actions);
        selection=ui.text("",12,Ui.GREEN);body.addView(selection);list=ui.column();body.addView(list);renderList();
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){query=s.toString();renderList();}public void afterTextChanged(Editable e){}});
        if(pool)action(body,"查看内置技能更新提示",()->task("正在检查内置技能更新…",api->object(api.call("GET","/skills/pool/builtin-notice",null)),r->notice("内置技能更新",r.optBoolean("has_updates")?"共 "+r.optInt("total_changes")+" 项变化\n\n"+noticeText(r):"内置技能暂无更新")));
    }
    private String noticeText(JSONObject r){StringBuilder s=new StringBuilder();for(String key:new String[]{"added","missing","updated","removed"}){JSONArray a=Json.array(r.opt(key));if(a.length()==0)continue;s.append(switch(key){case "added"->"新增";case "missing"->"未导入";case "updated"->"可更新";default->"源中已移除";}).append("：\n");for(int i=0;i<a.length();i++)s.append(Json.object(a.opt(i)).optString("name")).append('\n');}return s.toString();}
    private Spinner compactSpinner(LinearLayout parent,List<String> options,String selected){Spinner s=new Spinner(this);ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,options);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(a);s.setSelection(Math.max(0,options.indexOf(selected)));parent.addView(s,new LinearLayout.LayoutParams(0,ui.dp(48),1));return s;}
    private void selectChanged(Spinner s,java.util.function.Consumer<String> done){s.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int i,long id){done.accept(String.valueOf(s.getSelectedItem()));}});}
    private boolean matches(JSONObject s){String q=query.trim().toLowerCase(Locale.ROOT);if(!(s.optString("name")+" "+s.optString("description")).toLowerCase(Locale.ROOT).contains(q))return false;if(!tag.equals("全部标签")&&!arrayContains(Json.array(s.opt("tags")),tag))return false;return switch(filter){case "已启用"->s.optBoolean("enabled");case "未启用"->!s.optBoolean("enabled");case "预加载"->s.optBoolean("preload");case "内置"->SkillLogic.builtin(s);case "外部"->s.optBoolean("external");case "自定义"->!SkillLogic.builtin(s)&&!s.optBoolean("external");case "自动同步"->s.optBoolean("auto_sync");default->true;};}
    private void renderList(){
        if(list==null||editing)return;list.removeAllViews();int shown=0;
        for(int i=0;i<skills.length();i++){JSONObject s=skills.optJSONObject(i);if(s==null||!matches(s))continue;shown++;String key=s.optString("name");LinearLayout c=card(list);LinearLayout head=ui.row();CheckBox choice=new CheckBox(this);choice.setChecked(selected.contains(key));choice.setContentDescription("选择技能 "+key);choice.setOnCheckedChangeListener((b,checked)->{if(checked)selected.add(key);else selected.remove(key);selection.setText("共 "+skills.length()+" 项 · 已选择 "+selected.size()+" 项");});head.addView(choice);TextView title=ui.heading(s.optString("emoji","")+" "+key,16);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));c.addView(head);summary(c,s.optString("description","暂无描述"));text(c,(pool?sourceLabel(s)+" · "+syncLabel(s.optString("sync_status")):(s.optBoolean("enabled")?"已启用":"未启用")+(s.optBoolean("preload")?" · 预加载":""))+" · "+s.optString("version_text",""));
            if(Json.array(s.opt("tags")).length()>0)text(c,"标签："+SkillLogic.join(Json.array(s.opt("tags"))));
            LinearLayout buttons=ui.row();buttons.addView(ui.button("查看 / 配置",null,false,v->open(key)),new LinearLayout.LayoutParams(0,-2,1));
            buttons.addView(ui.button(pool?"分发":s.optBoolean("enabled")?"禁用":"启用",null,false,v->{if(pool)broadcast(List.of(key));else mutate("POST",path(key)+(s.optBoolean("enabled")?"/disable":"/enable"),null,()->load(false));}),new LinearLayout.LayoutParams(0,-2,1));c.addView(buttons);
        }selection.setText("共 "+skills.length()+" 项 · 已选择 "+selected.size()+" 项");if(shown==0)text(list,skills.length()==0?"暂无技能":"没有匹配的技能");
    }
    private String sourceLabel(JSONObject s){return s.optBoolean("external")?"外部技能":SkillLogic.builtin(s)?"内置技能":"自定义技能";}
    private String syncLabel(String s){return switch(s){case "synced"->"已同步";case "outdated"->"可更新";case "not_synced"->"未同步";case "conflict"->"存在冲突";default->"—";};}
    private void open(String key){task("正在读取技能详情…",api->object(api.call("GET",path(key),null)),this::editor);}
    private void editor(JSONObject value){
        editing=true;detail=value;originalName=value.optString("name");originalConfig=Json.text(value.optJSONObject("config")==null?new JSONObject():value.optJSONObject("config"));body.removeAllViews();if(agentSelector!=null)agentSelector.setEnabled(false);scroll.scrollTo(0,0);
        LinearLayout meta=card(body);meta.addView(ui.heading(originalName,21));text(meta,value.optString("description",""));text(meta,sourceLabel(value)+" · "+value.optString("version_text",""));text(meta,"来源："+value.optString("installed_from",value.optString("external_path","—")));if(value.optJSONObject("requirements")!=null)text(meta,"依赖要求\n"+Json.text(value.opt("requirements")));
        LinearLayout document=card(body);document.addView(ui.heading("技能内容",18));ui.gap(document,8);text(document,"SKILL.md · 只读预览");
        TextView content=ui.text("",14,Ui.INK);content.setTag("skill-markdown-preview");content.setContentDescription("技能 Markdown 正文（只读）");content.setTextIsSelectable(true);content.setLineSpacing(ui.dp(4),1);
        String rendered=AgentDocument.markdown(value.optString("content"));if(rendered.isBlank())content.setText("暂无正文");else markdown.setMarkdown(content,rendered);document.addView(content,new LinearLayout.LayoutParams(-1,-2));
        config=field(body,"技能配置（JSON 对象）",originalConfig,true);config.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO);config.setTypeface(android.graphics.Typeface.MONOSPACE);
        action(body,"保存配置",this::saveConfig);action(body,"标签："+SkillLogic.join(Json.array(value.opt("tags"))),()->leaveEditor(()->editTags(value)));
        if(!pool){
            action(body,"可用渠道："+SkillLogic.join(Json.array(value.opt("channels"))),()->leaveEditor(()->channels(value)));
            action(body,value.optBoolean("preload")?"关闭预加载":"开启预加载",()->leaveEditor(()->mutate("PUT",path(originalName)+"/preload",Json.obj("preload",!value.optBoolean("preload")),()->open(originalName))));
            text(body,"预加载会将完整技能内容注入系统提示词，增加上下文消耗。");
            action(body,value.optBoolean("enabled")?"禁用技能":"启用技能",()->leaveEditor(()->mutate("POST",path(originalName)+(value.optBoolean("enabled")?"/disable":"/enable"),null,()->open(originalName))));
            action(body,"上传到技能池",()->leaveEditor(()->transfer(List.of(originalName),true,new JSONArray(),false)));
        }else{
            text(body,"同步状态："+syncLabel(value.optString("sync_status")));action(body,"自动更新与同步",()->leaveEditor(()->automation(value)));
            if(SkillLogic.builtin(value))action(body,"更新内置技能 / 切换语言",()->leaveEditor(()->builtinLanguage(value)));
            action(body,"分发到智能体",()->leaveEditor(()->broadcast(List.of(originalName))));
        }
        action(body,"删除技能",()->leaveEditor(()->confirm("删除技能",deleteMessage(List.of(originalName)),()->mutate("DELETE",path(originalName),null,()->load(false)))));
        action(body,"返回技能列表",()->leaveEditor(()->load(false)));
    }
    private boolean dirty(){return editing&&config!=null&&!originalConfig.equals(config.getText().toString());}
    private void leaveEditor(Runnable next){if(busy)return;if(dirty())confirm("放弃未保存的配置？","当前技能配置尚未保存。",next);else next.run();}
    @Override public void onBackPressed(){if(busy){super.onBackPressed();return;}if(editing)leaveEditor(()->load(false));else super.onBackPressed();}
    private void saveConfig(){
        JSONObject cfg;try{cfg=SkillLogic.config(config.getText().toString());}catch(IllegalArgumentException e){notice("请检查技能配置",e.getMessage());return;}
        String skillName=originalName;
        // Dedicated manifest endpoint: never round-trip SKILL.md, even an old unchanged snapshot.
        task("正在保存技能配置…",api->object(api.call("PUT",path(skillName)+"/config",Json.obj("config",cfg))),r->{toast("配置已保存");open(skillName);},e->{
            status.setText("保存失败，配置草稿已保留");
            notice("配置未保存",e instanceof ApiClient.ApiException a?"服务器未接受配置（"+a.status+"），请核对配置后重试。":"网络中断，保存结果未确认。配置草稿已保留，请刷新确认后再提交。");
        });
    }
    private void editTags(JSONObject value){LinearLayout form=ui.column();ui.padding(form,16,8);EditText input=field(form,"标签（逗号分隔，最多 8 个）",SkillLogic.join(Json.array(value.opt("tags"))),false);androidx.appcompat.app.AlertDialog d=new MaterialAlertDialogBuilder(this).setTitle("编辑标签").setView(form).setNegativeButton("取消",null).setPositiveButton("保存",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(b->{try{JSONArray tags=SkillLogic.tags(input.getText().toString());d.dismiss();mutate("PUT",path(value.optString("name"))+"/tags",tags,()->open(value.optString("name")));}catch(IllegalArgumentException e){input.setError(e.getMessage());}}));d.show();}
    private void channels(JSONObject value){task("正在读取可用渠道…",api->array(api.call("GET","/config/channels/types",null)),types->{ArrayList<String> options=new ArrayList<>(List.of("all"));for(int i=0;i<types.length();i++)if(!options.contains(types.optString(i)))options.add(types.optString(i));JSONArray saved=Json.array(value.opt("channels"));for(int i=0;i<saved.length();i++)if(!options.contains(saved.optString(i)))options.add(saved.optString(i));boolean[] checked=new boolean[options.size()];for(int i=0;i<checked.length;i++)checked[i]=saved.length()==0?i==0:arrayContains(saved,options.get(i));ArrayList<String> labels=new ArrayList<>(options);labels.set(0,"全部渠道");multi("可用渠道（全部优先）",labels,checked,result->{JSONArray chosen=new JSONArray();if(result[0])chosen.put("all");else for(int i=1;i<result.length;i++)if(result[i])chosen.put(options.get(i));if(chosen.length()==0){notice("请选择渠道","至少选择一个渠道，或选择全部渠道。");return;}mutate("PUT",path(value.optString("name"))+"/channels",chosen,()->open(value.optString("name")));});});}
    private static boolean arrayContains(JSONArray a,String s){for(int i=0;i<a.length();i++)if(s.equals(a.optString(i)))return true;return false;}
    private void mutate(String method,String endpoint,Object data,Runnable next){task("正在保存…",api->{JSONObject r=object(api.call(method,endpoint,data));if(endpoint.endsWith("/enable")||endpoint.endsWith("/batch-enable")){ArrayList<String> names=new ArrayList<>();if(data instanceof JSONArray a){for(int i=0;i<a.length();i++)names.add(a.optString(i));}else names.add(android.net.Uri.decode(endpoint.substring(endpoint.lastIndexOf('/',endpoint.length()-8)+1,endpoint.length()-7)));SkillLogic.withWarnings(api,r,names);}return r;},r->{String message=SkillLogic.result(r);if(!message.equals("操作完成"))notice("操作结果",message);else toast(message);next.run();});}
    private void batchMenu(){if(busy)return;String[] actions=pool?new String[]{"全选筛选结果","清空选择","分发已选技能","删除已选技能"}:new String[]{"全选筛选结果","清空选择","启用已选技能","禁用已选技能","上传已选到技能池","删除已选技能"};new MaterialAlertDialogBuilder(this).setTitle("批量管理 · 已选 "+selected.size()).setItems(actions,(d,index)->{
        if(index==0){for(int i=0;i<skills.length();i++){JSONObject s=Json.object(skills.opt(i));if(matches(s))selected.add(s.optString("name"));}renderList();return;}if(index==1){selected.clear();renderList();return;}if(selected.isEmpty()){toast("请先选择技能");return;}List<String> names=new ArrayList<>(selected);
        if(pool&&index==2){broadcast(names);return;}if(!pool&&index==4){transfer(names,true,new JSONArray(),false);return;}
        String op=pool||index==5?"delete":index==2?"enable":"disable";Runnable execute=()->mutate("POST",prefix()+"/batch-"+op,new JSONArray(names),()->load(false));if(op.equals("delete"))confirm("批量删除",deleteMessage(names),execute);else execute.run();
    }).show();}
    private String deleteMessage(List<String> names){StringBuilder msg=new StringBuilder("将删除以下技能：\n"+String.join("\n",names));if(pool){msg.append("\n智能体中已有的副本仍会保留。");for(int i=0;i<skills.length();i++){JSONObject s=Json.object(skills.opt(i));if(names.contains(s.optString("name"))&&s.optBoolean("external"))msg.append("\n外部技能 ").append(s.optString("name")).append(" 的真实目录也将删除：").append(s.optString("external_path"));}}return msg.toString();}
    private void downloadPicker(){task("正在读取技能池…",api->array(api.call("GET","/skills/pool",null)),data->{ArrayList<String> names=new ArrayList<>(),labels=new ArrayList<>();for(int i=0;i<data.length();i++){JSONObject s=Json.object(data.opt(i));names.add(s.optString("name"));labels.add(s.optString("name")+" · "+s.optString("version_text",""));}if(names.isEmpty()){notice("技能池","暂无可下载的技能");return;}multi("从技能池下载到 "+agent,labels,new boolean[names.size()],checks->{ArrayList<String> picked=new ArrayList<>();for(int i=0;i<checks.length;i++)if(checks[i])picked.add(names.get(i));if(!picked.isEmpty())transfer(picked,false,Json.arr(Json.obj("workspace_id",agent)),false);});});}
    private void broadcast(List<String> names){task("正在读取智能体…",api->array(api.call("GET","/skills/workspaces",null)),workspaces->{ArrayList<String> ids=new ArrayList<>(),labels=new ArrayList<>();for(int i=0;i<workspaces.length();i++){JSONObject ws=Json.object(workspaces.opt(i));ids.add(ws.optString("agent_id"));labels.add(ws.optString("agent_name",ws.optString("agent_id"))+" · "+ws.optString("agent_id"));}if(ids.isEmpty()){notice("分发技能","没有可用智能体");return;}labels.add(0,"全部智能体");multi("分发 "+names.size()+" 个技能",labels,new boolean[labels.size()],checked->{JSONArray targets=new JSONArray();if(!checked[0])for(int i=1;i<checked.length;i++)if(checked[i])targets.put(Json.obj("workspace_id",ids.get(i-1)));if(!checked[0]&&targets.length()==0){toast("请选择目标智能体");return;}transfer(names,false,targets,checked[0]);});});}
    private void transfer(List<String> names,boolean upload,JSONArray targets,boolean all){
        String capturedAgent=agent;String endpoint=upload?"/skills/pool/upload":"/skills/pool/download";
        task("正在检查传输冲突…",api->{JSONArray plans=new JSONArray(),conflicts=new JSONArray();for(String skill:names){JSONObject p=Json.obj("skill_name",skill,"preview_only",true,"overwrite",false);if(upload)Json.put(p,"workspace_id",capturedAgent);else{Json.put(p,"targets",targets);Json.put(p,"all_workspaces",all);}try{JSONObject r=object(api.call("POST",endpoint,p));JSONArray c=Json.array(r.opt("conflicts"));if(c.length()>0)conflicts.put(Json.obj("skill",skill,"detail",c));plans.put(p);}catch(ApiClient.ApiException e){JSONObject d=Json.object(e.detail);if(e.status!=409)throw e;conflicts.put(Json.obj("skill",skill,"detail",d));plans.put(p);}}return Json.obj("plans",plans,"conflicts",conflicts);},preview->{JSONArray plans=Json.array(preview.opt("plans")),conflicts=Json.array(preview.opt("conflicts"));Runnable execute=()->executeTransfers(endpoint,plans,conflicts);if(conflicts.length()>0)confirm("确认覆盖冲突技能",Json.text(conflicts)+"\n确认后仅覆盖本次列出的冲突；其余技能按正常传输处理。",execute);else execute.run();});
    }
    private void executeTransfers(String endpoint,JSONArray plans,JSONArray conflicts){task("正在传输技能…",api->{StringBuilder report=new StringBuilder();for(int i=0;i<plans.length();i++){JSONObject p=Json.copy(Json.object(plans.opt(i)));String skill=p.optString("skill_name");boolean overwrite=false;for(int j=0;j<conflicts.length();j++)if(skill.equals(Json.object(conflicts.opt(j)).optString("skill")))overwrite=true;Json.put(p,"preview_only",false);Json.put(p,"overwrite",overwrite);try{report.append(skill).append("：").append(SkillLogic.result(SkillLogic.withWarnings(api,object(api.call("POST",endpoint,p)),List.of(skill)))).append("\n");}catch(ApiClient.ApiException e){if(e.status==401)throw e;report.append(skill).append("：失败，").append(e.getMessage()).append('\n');}catch(Exception e){report.append(skill).append("：结果未确认，").append(e.getMessage()).append('\n');}}return report.toString();},report->{notice("传输结果",report);load(false);});}
    private void builtins(){task("正在读取内置技能…",api->array(api.call("GET","/skills/pool/builtin-sources",null)),sources->{LinearLayout form=ui.column();ui.padding(form,16,8);ArrayList<CheckBox> boxes=new ArrayList<>();ArrayList<Spinner> langs=new ArrayList<>();ArrayList<String> names=new ArrayList<>();for(int i=0;i<sources.length();i++){JSONObject s=Json.object(sources.opt(i));names.add(s.optString("name"));boxes.add(check(form,s.optString("name")+" · "+s.optString("status","")+" · "+s.optString("version_text",""),false));JSONArray raw=Json.array(s.opt("available_languages"));ArrayList<String> languages=new ArrayList<>();for(int j=0;j<raw.length();j++)languages.add(raw.optString(j));if(languages.isEmpty())languages.add("en");langs.add(select(form,"语言",languages,languages.indexOf("zh")));text(form,s.optString("description",""));}ScrollView scroll=new ScrollView(this);scroll.addView(form);new MaterialAlertDialogBuilder(this).setTitle("导入内置技能").setView(scroll).setNegativeButton("取消",null).setPositiveButton("导入",(d,w)->{JSONArray imports=new JSONArray();for(int i=0;i<boxes.size();i++)if(boxes.get(i).isChecked())imports.put(Json.obj("skill_name",names.get(i),"language",String.valueOf(langs.get(i).getSelectedItem())));if(imports.length()>0)importBuiltins(imports,false);else toast("未选择技能");}).show();});}
    private void importBuiltins(JSONArray imports,boolean overwrite){task("正在导入内置技能…",api->{JSONObject result=object(api.call("POST","/skills/pool/import-builtin",Json.obj("imports",imports,"overwrite_conflicts",overwrite)));ArrayList<String> names=new ArrayList<>();for(int i=0;i<imports.length();i++)names.add(Json.object(imports.opt(i)).optString("skill_name"));return SkillLogic.withWarnings(api,result,names);},r->{notice("导入结果",SkillLogic.result(r));load(false);},e->{JSONObject d=e instanceof ApiClient.ApiException a?Json.object(a.detail):new JSONObject();if(!overwrite&&Json.array(d.opt("conflicts")).length()>0)confirm("覆盖内置技能冲突？",Json.text(d.opt("conflicts")),()->importBuiltins(imports,true));else showError(e);});}
    private void builtinLanguage(JSONObject skill){JSONArray raw=Json.array(skill.opt("available_builtin_languages"));ArrayList<String> languages=new ArrayList<>();for(int i=0;i<raw.length();i++)languages.add(raw.optString(i));if(languages.isEmpty())languages.add(skill.optString("builtin_language","en"));new MaterialAlertDialogBuilder(this).setTitle("更新内置技能 / 切换语言").setItems(languages.toArray(new String[0]),(d,w)->confirm("确认更新内置内容","将使用 "+languages.get(w)+" 版本覆盖技能内容。已启用的自动同步可能更新智能体副本。",()->mutate("POST",path(skill.optString("name"))+"/update-builtin",Json.obj("language",languages.get(w)),()->open(skill.optString("name"))))).show();}
    private void automation(JSONObject skill){task("正在读取同步目标…",api->array(api.call("GET","/skills/workspaces",null)),workspaces->{LinearLayout form=ui.column();ui.padding(form,16,8);CheckBox update=SkillLogic.builtin(skill)?check(form,"自动更新内置技能",skill.optBoolean("auto_update")):null;CheckBox sync=check(form,"自动同步到智能体",skill.optBoolean("auto_sync"));JSONArray old=Json.array(skill.opt("auto_sync_targets"));CheckBox all=check(form,"所有已安装该技能的智能体",old.length()==0);ArrayList<CheckBox> boxes=new ArrayList<>();ArrayList<String> ids=new ArrayList<>();for(int i=0;i<workspaces.length();i++){JSONObject ws=Json.object(workspaces.opt(i));String id=ws.optString("agent_id");ids.add(id);boxes.add(check(form,ws.optString("agent_name",id)+" · "+id,arrayContains(old,id)));}for(int i=0;i<old.length();i++)if(!ids.contains(old.optString(i))){ids.add(old.optString(i));boxes.add(check(form,old.optString(i)+"（当前目录不可见）",true));}for(CheckBox box:boxes)box.setEnabled(!all.isChecked());all.setOnCheckedChangeListener((button,checked)->{for(CheckBox box:boxes)box.setEnabled(!checked);});text(form,"默认同步已有副本，也可指定智能体。开启或修改设置会立即执行同步，可能覆盖目标技能副本。");ScrollView sc=new ScrollView(this);sc.addView(form);androidx.appcompat.app.AlertDialog dialog=new MaterialAlertDialogBuilder(this).setTitle("自动更新与同步").setView(sc).setNegativeButton("取消",null).setPositiveButton("保存",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(button->{JSONArray targets=new JSONArray();for(int i=0;i<boxes.size();i++)if(boxes.get(i).isChecked())targets.put(ids.get(i));if(!all.isChecked()&&targets.length()==0){toast("请选择同步目标，或选择所有已有副本");return;}JSONObject payload=SkillLogic.automation(skill,update!=null&&update.isChecked(),sync.isChecked(),all.isChecked()?new JSONArray():targets);dialog.dismiss();if(payload.length()==0){toast("设置未变化");return;}confirm("确认自动处理设置",sync.isChecked()?"将对选定智能体执行自动同步。":"保存自动处理设置。",()->mutate("PUT",path(skill.optString("name"))+"/automation",payload,()->open(skill.optString("name"))));}));dialog.show();});}
}
